In [1]:
import pandas as pd
import numpy as np

In [2]:
dataSet = pd.read_csv("mushrooms.csv", header = 0)

In [3]:
dataSet

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [4]:
lst = {'BLACK':[1],
       'BROWN':[2],
       'BUFF':[3],
       'CHOCOLATE':[4],
       'CINNAMON':[5],
       'GRAY':[6],
       'GREEN':[7],
       'ORANGE':[8],
       'PINK':[9],
       'PURPLE':[10],
       'RED':[11],
       'WHITE':[12],
       'YELLOW':[13]
      }
farba = pd.DataFrame(lst)

farba

BLACK  BROWN  BUFF  CHOCOLATE  CINNAMON  GRAY  GREEN  ORANGE  PINK  PURPLE  \
0      1      2     3          4         5     6      7       8     9      10   

   RED  WHITE  YELLOW  
0   11     12      13

In [5]:
# farba hlavicky hribu - Cap
train1 = np.where(dataSet.iloc[:,3]=='n',farba.iloc[0]['BROWN'],( # brown
            np.where(dataSet.iloc[:,3]=='b',farba.iloc[0]['BUFF'],( # buff
                np.where(dataSet.iloc[:,3]=='c',farba.iloc[0]['CINNAMON'],( # cinnamon
                    np.where(dataSet.iloc[:,3]=='g',farba.iloc[0]['GRAY'],( # gray
                        np.where(dataSet.iloc[:,3]=='r',farba.iloc[0]['GREEN'],( # green
                            np.where(dataSet.iloc[:,3]=='p',farba.iloc[0]['PINK'],( # pink
                                np.where(dataSet.iloc[:,3]=='u',farba.iloc[0]['PURPLE'],( # purple
                                    np.where(dataSet.iloc[:,3]=='e',farba.iloc[0]['RED'],( # red
                                        np.where(dataSet.iloc[:,3]=='w',farba.iloc[0]['WHITE'],farba.iloc[0]['YELLOW']))))))))))))))))) # white,  yellow 
train1

array([ 2, 13, 12, ...,  2,  2,  2], dtype=int64)

In [6]:
# farba lupenov pod hlavickou hribu - Gill
train2 = np.where(dataSet.iloc[:,9]=='k',farba.iloc[0]['BLACK'],( # black   
            np.where(dataSet.iloc[:,9]=='n',farba.iloc[0]['BROWN'],( # brown 
                np.where(dataSet.iloc[:,9]=='b',farba.iloc[0]['BUFF'],( # buff  
                    np.where(dataSet.iloc[:,9]=='h',farba.iloc[0]['CHOCOLATE'],( # chocolate
                        np.where(dataSet.iloc[:,9]=='g',farba.iloc[0]['GRAY'],( # gray
                            np.where(dataSet.iloc[:,9]=='r',farba.iloc[0]['GREEN'],( # green
                                np.where(dataSet.iloc[:,9]=='o',farba.iloc[0]['ORANGE'],( # orange
                                    np.where(dataSet.iloc[:,9]=='p',farba.iloc[0]['PINK'],( # pink
                                        np.where(dataSet.iloc[:,9]=='u',farba.iloc[0]['PURPLE'],( # purple
                                            np.where(dataSet.iloc[:,9]=='e',farba.iloc[0]['RED'],( # red
                                                np.where(dataSet.iloc[:,9]=='w',farba.iloc[0]['WHITE'],farba.iloc[0]['YELLOW']))))))))))))))))))))) # white,  yellow
train2 

array([ 1,  1,  2, ...,  2,  3, 13], dtype=int64)

In [7]:
# farba stonky nad prstenom hriba - Stalk above ring
train3 = np.where(dataSet.iloc[:,14]=='n',1,( # brown 
            np.where(dataSet.iloc[:,14]=='b',2,( # buff
                np.where(dataSet.iloc[:,14]=='c',3,( # cinnamon
                    np.where(dataSet.iloc[:,14]=='g',4,( # gray
                        np.where(dataSet.iloc[:,14]=='o',5,( # orange
                            np.where(dataSet.iloc[:,14]=='p',6,( # pink
                                np.where(dataSet.iloc[:,14]=='e',7,( # red
                                    np.where(dataSet.iloc[:,14]=='w',8,9))))))))))))))) # white, 9 = yellow
train3

array([8, 8, 8, ..., 5, 8, 5])

In [8]:
# farba stonky pod prstenom hriba - Stalk bellow ring
train4 = np.where(dataSet.iloc[:,15]=='n',farba.iloc[0]['BROWN'],( # brown 
            np.where(dataSet.iloc[:,15]=='b',farba.iloc[0]['BUFF'],( # buff
                np.where(dataSet.iloc[:,15]=='c',farba.iloc[0]['CINNAMON'],( # cinnamon
                    np.where(dataSet.iloc[:,15]=='g',farba.iloc[0]['GRAY'],( # gray
                        np.where(dataSet.iloc[:,15]=='o',farba.iloc[0]['ORANGE'],( # orange
                            np.where(dataSet.iloc[:,15]=='p',farba.iloc[0]['PINK'],( # pink
                                np.where(dataSet.iloc[:,15]=='e',farba.iloc[0]['RED'],( # red
                                    np.where(dataSet.iloc[:,15]=='w',farba.iloc[0]['WHITE'],farba.iloc[0]['YELLOW']))))))))))))))) # white, 9 = yellow
train4

array([12, 12, 12, ...,  8, 12,  8], dtype=int64)

In [9]:
# farba prstena hribu - Veil
train5 = np.where(dataSet.iloc[:,17]=='n',farba.iloc[0]['BROWN'],( # brown  
            np.where(dataSet.iloc[:,17]=='o',farba.iloc[0]['ORANGE'],( # orange 
                np.where(dataSet.iloc[:,17]=='w',farba.iloc[0]['WHITE'],farba.iloc[0]['YELLOW']))))) # white, 4 = yellow
                   
train5

array([12, 12, 12, ...,  8, 12,  8], dtype=int64)

In [10]:
# farba vytrusov hribu na papieri - Spore print
train6 = np.where(dataSet.iloc[:,20]=='k',farba.iloc[0]['BLACK'],( # black   
            np.where(dataSet.iloc[:,20]=='n',farba.iloc[0]['BROWN'],( # brown   
                np.where(dataSet.iloc[:,20]=='b',farba.iloc[0]['BUFF'],( # buff   
                    np.where(dataSet.iloc[:,20]=='h',farba.iloc[0]['CHOCOLATE'],( # chocolate  
                        np.where(dataSet.iloc[:,20]=='r',farba.iloc[0]['GREEN'],( # green  
                            np.where(dataSet.iloc[:,20]=='o',farba.iloc[0]['ORANGE'],( # orange   
                                np.where(dataSet.iloc[:,20]=='u',farba.iloc[0]['PURPLE'],( # purple   
                                    np.where(dataSet.iloc[:,20]=='w',farba.iloc[0]['WHITE'],farba.iloc[0]['YELLOW']))))))))))))))) # white, 9 = yellow 
                   
train6

array([ 1,  2,  2, ...,  3, 12,  8], dtype=int64)

In [11]:
# Spojenie vsetkych mnozin
trainX = np.stack((train1, train2, train3, train4, train5, train6), axis=1)
trainX

array([[ 2,  1,  8, 12, 12,  1],
       [13,  1,  8, 12, 12,  2],
       [12,  2,  8, 12, 12,  2],
       ...,
       [ 2,  2,  5,  8,  8,  3],
       [ 2,  3,  8, 12, 12, 12],
       [ 2, 13,  5,  8,  8,  8]], dtype=int64)

In [12]:
# kategoricke premenne, urcujeme ci je hrib jedlý alebo otrávený
trainY = np.where((dataSet.iloc[:,0])=='e',1,0) # ak jedly, tak 1, ak jedovaty tak 0

In [13]:
trainY

array([0, 1, 1, ..., 1, 0, 1])

In [14]:
from keras.utils import np_utils
from keras.utils import to_categorical

In [15]:
# nastavenie kategorie vsetkym typom hribom 
kategorickaPremenna = np_utils.to_categorical(trainY)
kategorickaPremenna

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [16]:
# potrebujeme model a vrstvy pre vypocty neuronovych sieti
from keras.models import Sequential # sekvencny model
from keras.layers import Dense # vrstvy - vstupna, skryta, vystupna

In [127]:
mojKerasModel = Sequential()

In [128]:
# vstupna vrstva bude s 30 neuronmi
# input_dim pocet dimenzii (vrstiev)
# 23 vstupuju
mojKerasModel.add(Dense(100, input_dim = 6, activation='tanh'))

# skryta vrstva
mojKerasModel.add(Dense(30, activation='tanh'))

# vystupna vrstva ma dve neurony lebo kategoricka premenna ma dve hodnoty 
mojKerasModel.add(Dense(2))
# model je pripraveny treba ho natrenovat

# pred trenovanim ho treba skompilovat
# param strata - loss napr. metoda najmensich stvorcov
# optimizer - na zaklade coho sa ma optimalizovat (adam byva naj)
# metrics - pridanie presnosti k vysledku
mojKerasModel.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])


# trenovanie parametrom trainX
# upravovat activation
mojKerasModel.fit(trainX, kategorickaPremenna, epochs=10, batch_size=50)

Epoch 1/10
163/163 [==============================] - 0s 517us/step - loss: 0.6443 - accuracy: 0.6627
Epoch 2/10
163/163 [==============================] - 0s 512us/step - loss: 0.1076 - accuracy: 0.8572
Epoch 3/10
163/163 [==============================] - 0s 512us/step - loss: 0.0882 - accuracy: 0.8987
Epoch 4/10
163/163 [==============================] - 0s 512us/step - loss: 0.0749 - accuracy: 0.9252
Epoch 5/10
163/163 [==============================] - 0s 519us/step - loss: 0.0710 - accuracy: 0.9274
Epoch 6/10
163/163 [==============================] - 0s 531us/step - loss: 0.0712 - accuracy: 0.9247
Epoch 7/10
163/163 [==============================] - 0s 519us/step - loss: 0.0640 - accuracy: 0.9321
Epoch 8/10
163/163 [==============================] - 0s 531us/step - loss: 0.0662 - accuracy: 0.9280
Epoch 9/10
163/163 [==============================] - 0s 512us/step - loss: 0.0634 - accuracy: 0.9308
Epoch 10/10
163/163 [==============================] - 0s 518us/step - loss: 0.058

optimiser sgd - loss: 0.1753 - accuracy: 0.8087

In [162]:
test_y = trainY[0:100]

test_x = trainX[0:100]

In [163]:
encoding_test_y = np_utils.to_categorical(test_y)

scores = mojKerasModel.evaluate(test_x, encoding_test_y)
print("\nAccuracy: %.2f%%" % (scores[1]*100))

4/4 [==============================] - 0s 667us/step - loss: 0.1395 - accuracy: 0.8300

Accuracy: 83.00%


In [164]:
# hlavicka, lupene pod hlavickou, stonka nad p, stonka pod p, prsten, vytrusy

# vzorka = np.array([[2,1, 8,12,12, 1]]) # [0.21112321, 0.91422325] P
# vzorka = np.array([[13,  1,  8, 12, 12,  2]]) # [0.17892213, 0.84764916] E

# vzorka = np.array([[2,3,8,12,12,12]]) # [0.9731052 , 0.04955696] P
# vzorka = np.array([[2, 13,  5,  8,  8,  8]]) # [0.1793459, 1.0192788] E
vzorka = np.array([[2,  2,  5,  8,  8,  3]]) # [0.36713922, 0.60136366] E

predictions = mojKerasModel.predict(vzorka)
predictions

array([[0.36713922, 0.60136366]], dtype=float32)

In [141]:
farba

BLACK  BROWN  BUFF  CHOCOLATE  CINNAMON  GRAY  GREEN  ORANGE  PINK  PURPLE  \
0      1      2     3          4         5     6      7       8     9      10   

   RED  WHITE  YELLOW  
0   11     12      13

In [148]:
trainX

array([[ 2,  1,  8, 12, 12,  1],
       [13,  1,  8, 12, 12,  2],
       [12,  2,  8, 12, 12,  2],
       ...,
       [ 2,  2,  5,  8,  8,  3],
       [ 2,  3,  8, 12, 12, 12],
       [ 2, 13,  5,  8,  8,  8]], dtype=int64)