In [2]:
import pandas as pd
import numpy as np

In [3]:
dataSet = pd.read_csv("mushrooms.csv", header = 0)

In [4]:
dataSet

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [5]:
# farba hlavicky hribu - Cap
train1 = np.where(dataSet.iloc[:,3]=='n',1,( # brown
            np.where(dataSet.iloc[:,3]=='b',2,( # buff
                np.where(dataSet.iloc[:,3]=='c',3,( # cinnamon
                    np.where(dataSet.iloc[:,3]=='g',4,( # gray
                        np.where(dataSet.iloc[:,3]=='r',5,( # green
                            np.where(dataSet.iloc[:,3]=='p',6,( # pink
                                np.where(dataSet.iloc[:,3]=='u',7,( # purple
                                    np.where(dataSet.iloc[:,3]=='e',8,( # red
                                        np.where(dataSet.iloc[:,3]=='w',9,10))))))))))))))))) # white, 10 = yellow 
train1

array([ 1, 10,  9, ...,  1,  1,  1])

In [6]:
# farba lupenov pod hlavickou hribu - Gill
train2 = np.where(dataSet.iloc[:,9]=='k',1,( # black   
            np.where(dataSet.iloc[:,9]=='n',2,( # brown 
                np.where(dataSet.iloc[:,9]=='b',3,( # buff  
                    np.where(dataSet.iloc[:,9]=='h',4,( # chocolate
                        np.where(dataSet.iloc[:,9]=='g',5,( # gray
                            np.where(dataSet.iloc[:,9]=='r',6,( # green
                                np.where(dataSet.iloc[:,9]=='o',7,( # orange
                                    np.where(dataSet.iloc[:,9]=='p',8,( # pink
                                        np.where(dataSet.iloc[:,9]=='u',9,( # purple
                                            np.where(dataSet.iloc[:,9]=='e',10,( # red
                                                np.where(dataSet.iloc[:,9]=='w',11,12))))))))))))))))))))) # white, 12 = yellow
train2 

array([ 1,  1,  2, ...,  2,  3, 12])

In [7]:
# farba stonky nad prstenom hriba - Stalk above ring
train3 = np.where(dataSet.iloc[:,14]=='n',1,( # brown 
            np.where(dataSet.iloc[:,14]=='b',2,( # buff
                np.where(dataSet.iloc[:,14]=='c',3,( # cinnamon
                    np.where(dataSet.iloc[:,14]=='g',4,( # gray
                        np.where(dataSet.iloc[:,14]=='o',5,( # orange
                            np.where(dataSet.iloc[:,14]=='p',6,( # pink
                                np.where(dataSet.iloc[:,14]=='e',7,( # red
                                    np.where(dataSet.iloc[:,14]=='w',8,9))))))))))))))) # white, 9 = yellow
train3

array([8, 8, 8, ..., 5, 8, 5])

In [8]:
# farba stonky pod prstenom hriba - Stalk bellow ring
train4 = np.where(dataSet.iloc[:,15]=='n',1,( # brown 
            np.where(dataSet.iloc[:,15]=='b',2,( # buff
                np.where(dataSet.iloc[:,15]=='c',3,( # cinnamon
                    np.where(dataSet.iloc[:,15]=='g',4,( # gray
                        np.where(dataSet.iloc[:,15]=='o',5,( # orange
                            np.where(dataSet.iloc[:,15]=='p',6,( # pink
                                np.where(dataSet.iloc[:,15]=='e',7,( # red
                                    np.where(dataSet.iloc[:,15]=='w',8,9))))))))))))))) # white, 9 = yellow
train4

array([8, 8, 8, ..., 5, 8, 5])

In [9]:
# farba prstena hribu - Veil
train5 = np.where(dataSet.iloc[:,17]=='n',1,( # brown  
            np.where(dataSet.iloc[:,17]=='o',2,( # orange 
                np.where(dataSet.iloc[:,17]=='w',3,4))))) # white, 4 = yellow
                   
train5

array([3, 3, 3, ..., 2, 3, 2])

In [10]:
# farba vytrusov hribu na papieri - Spore print
train6 = np.where(dataSet.iloc[:,20]=='k',1,( # black   
            np.where(dataSet.iloc[:,20]=='n',2,( # brown   
                np.where(dataSet.iloc[:,20]=='b',3,( # buff   
                    np.where(dataSet.iloc[:,20]=='h',4,( # chocolate  
                        np.where(dataSet.iloc[:,20]=='r',5,( # green  
                            np.where(dataSet.iloc[:,20]=='o',6,( # orange   
                                np.where(dataSet.iloc[:,20]=='u',7,( # purple   
                                    np.where(dataSet.iloc[:,20]=='w',8,9))))))))))))))) # white, 9 = yellow 
                   
train6

array([1, 2, 2, ..., 3, 8, 6])

In [11]:
# Spojenie vsetkych mnozin
trainX = np.stack((train1, train2, train3, train4, train5, train6), axis=1)
trainX

array([[ 1,  1,  8,  8,  3,  1],
       [10,  1,  8,  8,  3,  2],
       [ 9,  2,  8,  8,  3,  2],
       ...,
       [ 1,  2,  5,  5,  2,  3],
       [ 1,  3,  8,  8,  3,  8],
       [ 1, 12,  5,  5,  2,  6]])

In [12]:
# kategoricke premenne, urcujeme ci je hrib jedlý alebo otrávený
trainY = np.where((dataSet.iloc[:,0])=='e',1,0) # ak jedly, tak 1, ak jedovaty tak 0

In [13]:
trainY

array([0, 1, 1, ..., 1, 0, 1])

In [14]:
from keras.utils import np_utils
from keras.utils import to_categorical

In [15]:
# nastavenie kategorie vsetkym typom hribom 
kategorickaPremenna = np_utils.to_categorical(trainY)
kategorickaPremenna

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [16]:
# potrebujeme model a vrstvy pre vypocty neuronovych sieti
from keras.models import Sequential # sekvencny model
from keras.layers import Dense # vrstvy - vstupna, skryta, vystupna

In [17]:
mojKerasModel = Sequential()

In [18]:
# vstupna vrstva bude s 30 neuronmi
# input_dim pocet dimenzii (vrstiev)
# 23 vstupuju
mojKerasModel.add(Dense(30, input_dim = 6, activation='tanh'))

In [19]:
# skryta vrstva
mojKerasModel.add(Dense(30, activation='tanh'))

In [20]:
# vystupna vrstva ma dve neurony lebo kategoricka premenna ma dve hodnoty 
mojKerasModel.add(Dense(2))
# model je pripraveny treba ho natrenovat

In [21]:
# pred trenovanim ho treba skompilovat
# param strata - loss napr. metoda najmensich stvorcov
# optimizer - na zaklade coho sa ma optimalizovat (adam byva naj)
# metrics - pridanie presnosti k vysledku
mojKerasModel.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])

In [22]:
# trenovanie parametrom trainX
# upravovat activation
mojKerasModel.fit(trainX, kategorickaPremenna)

254/254 [==============================] - 0s 447us/step - loss: 0.2200 - accuracy: 0.7950


In [24]:
# toto je pokus 

a = 10